const itemData =[
  {
    id:1,
    name:'Cocacola Can 200ML',
    description:'Made by cocacola and its the most powerfer cola can even made beacause it was made by cocacola',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/a/product-0001.png'),
    shopicon:require('../assets/demo/a/profile.jpg'),
    price: 5,   
  },
  {
    id:2,
    name:'Cocacola Bottle 1.5L',
    description:'Made by cocacola and its the most powerfer cola can even made beacause it was made by cocacola',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/a/product-0002.jpg'),
    shopicon:require('../assets/demo/a/profile.jpg'),
    price: 10,   
  },
  {
    id:3,
    name:'Cocacola Bottle 2.5L',
    description:'Made by cocacola and its the most powerfer cola can even made beacause it was made by cocacola',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/a/product-0003.jpg'),
    shopicon:require('../assets/demo/a/profile.jpg'),
    price: 15,   
  },
  {
    id:4,
    name:'Cocacola Bottle 250ML',
    description:'Made by cocacola and its the most powerfer cola can even made beacause it was made by cocacola',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/a/product-0004.jpg'),
    shopicon:require('../assets/demo/a/profile.jpg'),
    price: 5,   
  },
  {
    id:5,
    name:'Cocacola Glass Bottle 250ML',
    description:'Made by cocacola and its the most powerfer cola can even made beacause it was made by cocacola',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/a/product-0005.jpg'),
    shopicon:require('../assets/demo/a/profile.jpg'),
    price: 5,   
  },
  {
    id:6,
    name:'Pepsi Can 200ML',
    description:'Made by pepsi and its the most powerfer cola can even made beacause it was made by pepsi',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/b/product-0001.jpg'),
    shopicon:require('../assets/demo/b/profile.jpg'),
    price: 5,   
  },
  {
    id:7,
    name:'Pepsi Bottle 1L',
    description:'Made by pepsi and its the most powerfer cola can even made beacause it was made by pepsi',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/b/product-0002.jpg'),
    shopicon:require('../assets/demo/b/profile.jpg'),
    price: 10,   
  },
  {
    id:8,
    name:'Pepsi Bottle 220ML',
    description:'Made by pepsi and its the most powerfer cola can even made beacause it was made by pepsi',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/b/product-0003.jpg'),
    shopicon:require('../assets/demo/b/profile.jpg'),
    price: 5,   
  },
  {
    id:9,
    name:'Pepsi Bottle 2L',
    description:'Made by pepsi and its the most powerfer cola can even made beacause it was made by pepsi',
    typeId:'3',
    homeId:'1002',
    imgurl:require('../assets/demo/b/product-0004.jpg'),
    shopicon:require('../assets/demo/b/profile.jpg'),
    price: 15,   
  },
  {
    id:10,
    name:'Cadbury Dairymilk 180g',
    description:'Made by cadbury and its the most powerfer chocolate can even made beacause it was made by cadbury',
    typeId:'4',
    homeId:'1002',
    imgurl:require('../assets/demo/c/product-0001.jpg'),
    shopicon:require('../assets/demo/c/profile.jpg'),
    price: 20,   
  },
  {
    id:11,
    name:'Cadbury Dairymilk 200g',
    description:'Made by cadbury and its the most powerfer chocolate can even made beacause it was made by cadbury',
    typeId:'4',
    homeId:'1002',
    imgurl:require('../assets/demo/c/product-0002.jpg'),
    shopicon:require('../assets/demo/c/profile.jpg'),
    price: 25,   
  },
  {
    id:12,
    name:'Cadbury Dairymilk Caramel',
    description:'Made by cadbury and its the most powerfer chocolate can even made beacause it was made by cadbury',
    typeId:'4',
    homeId:'1002',
    imgurl:require('../assets/demo/c/product-0003.jpg'),
    shopicon:require('../assets/demo/c/profile.jpg'),
    price: 25,   
  },
  {
    id:13,
    name:'Cadbury Dairymilk mini',
    description:'Made by cadbury and its the most powerfer chocolate can even made beacause it was made by cadbury',
    typeId:'4',
    homeId:'1002',
    imgurl:require('../assets/demo/c/product-0004.jpg'),
    shopicon:require('../assets/demo/c/profile.jpg'),
    price: 80,   
  },
   
]

export default itemData